import "../Styles/welcome.css";

function Welcome() {
	return (
		<div className="welcome">
			<div className="hero">
				<h1 className="text-center header">
					Come join the{" "}
					<span>
						movement
						<img src="/Images/Icons/loader.png" alt="loader" />
					</span>
					<br /> with BroadFi.
				</h1>
				<div className="btns">
					<a href="/homepage" className="btn btn-danger">
						<img
							src="/Images/Icons/headphones.png"
							alt="headphones"
						/>
						Start Now!
					</a>
				</div>
			</div>
			<div className="what-is container">
				<h2>What is BroadFi?</h2>
				<p>
					BroadFi is an innovative gamified SocialFi platform that
					revolutionizes audio content engagement. It empowers
					creators and users through gamified remix challenges,
					decentralized voting, and revenue-sharing models. By staking
					tokens, users vote for their favorite remixes and earn
					rewards from the content they listen to, fostering a
					collaborative and rewarding ecosystem for creators,
					listeners, and investors alike.
				</p>
			</div>
			<div className="problem container">
				<h6 className="tagline">The problem</h6>
				<h2>The issue we're trying to solve.</h2>
				<p>
					The traditional music and podcasting industries often lack
					transparency and equitable revenue-sharing mechanisms.
					Creators struggle to monetize their content effectively,
					while listeners rarely benefit from their engagement.
					Moreover, platforms seldom offer interactive gamified
					challenges that incentivize community participation and
					creativity.
				</p>
			</div>
			<div className="solution container">
				<h6 className="tagline">The solution</h6>
				<h2>How we will solve that</h2>
				<p>
					BroadFi bridges the gap by creating a decentralized platform
					where creators can engage in gamified remix and podcast
					challenges, while listeners actively participate by voting
					and staking tokens.
				</p>
			</div>

			<div className="choice container">
				<div className="text">
					<h6 className="tagline">Why choose us?</h6>
					<h2>How BroadFi works</h2>
					<p className="mt-1">
						BroadFi allows creators to participate in remix or
						podcast challenges by submitting their work. Users stake
						tokens to vote for their favorite content, determining
						the winner.
					</p>
				</div>
				<div className="image">
					<img src="/Images/welcome-illustration.png" alt="Welcome" />
				</div>
			</div>

			<div className="features container text-center">
				<h6 className="tagline">What Broadfi offers</h6>
				<h2>Why use BroadFi?</h2>
				<div className="row">
					<div className="feature col-3">
						<img
							src="/Images/Icons/cpu.png"
							alt="Gamified Remix and Podcast Challenges"
						/>
						<h4>Gamified Remix and Podcast Challenges</h4>
						<p>
							Encourages creativity and competition among
							creators.
						</p>
					</div>
					<div className="feature col-3">
						<img
							src="/Images/Icons/archive.png"
							alt="Decentralized Voting System"
						/>
						<h4>Decentralized Voting System</h4>
						<p>
							Users stake tokens to vote for their favorite
							content.
						</p>
					</div>
					<div className="feature col-3">
						<img
							src="/Images/Icons/dollar-sign.png"
							alt="Revenue Sharing"
						/>
						<h4>Revenue Sharing</h4>
						<p>
							Staked tokens allow listeners to earn a share of
							revenue generated by played content.
						</p>
					</div>
					<div className="feature col-3">
						<img
							src="/Images/Icons/bar-chart.png"
							alt="Top Chart Trends"
						/>
						<h4>Top Chart Trends</h4>
						<p>
							Highlights the most popular remixes and podcasts
							voted by the community.
						</p>
					</div>
					<div className="feature col-3">
						<img
							src="/Images/Icons/droplet.png"
							alt="Tokenized Economy"
						/>
						<h4>Tokenized Economy</h4>
						<p>
							Drives platform engagement and rewards users for
							participation.
						</p>
					</div>
					<div className="feature col-3">
						<img
							src="/Images/Icons/user.png"
							alt="Creator Dashboard"
						/>
						<h4>Creator Dashboard</h4>
						<p>Provides analytics and insights for creators.</p>
					</div>
					<div className="feature col-3">
						<img
							src="/Images/Icons/link.png"
							alt="On-Chain Transparency"
						/>
						<h4>On-Chain Transparency</h4>
						<p>Ensures secure and verifiable transactions.</p>
					</div>
				</div>
			</div>
		</div>
	);
}

export default Welcome;
